CREATE OR REPLACE PROCEDURE RESET_SEQUENCE
(
    P_TABLE_NAME IN VARCHAR2,
    P_ID_COLUMN IN VARCHAR2,
    P_SEQUENCE_NAME IN VARCHAR2
)
IS
    vSeqObjCount NUMBER;
    vSql VARCHAR2(32767);
BEGIN
    SELECT COUNT(1) INTO vSeqObjCount FROM USER_SEQUENCES WHERE SEQUENCE_NAME = P_SEQUENCE_NAME;
    DBMS_OUTPUT.PUT_LINE('vSeqObjCount: ' || vSeqObjCount);

    IF (vSeqObjCount = 0) THEN
        DBMS_OUTPUT.PUT_LINE('シーケンス「' || P_SEQUENCE_NAME || '」を作成');
        vSql := 'CREATE SEQUENSE ' || P_SEQUENCE_NAME || ';';
        EXECUTE IMMEDIATE vSql;
        RETURN;
    END IF;

    DBMS_OUTPUT.PUT_LINE('シーケンス「' || P_SEQUENCE_NAME || '」の調整');
END;
