CREATE OR REPLACE PROCEDURE DELETE_RESTAURANT
(
    P_MAIL_ADDRESS IN VARCHAR2
)
IS
    vSql VARCHAR2(32767);
    vUserId NUMBER;
    vRestaurantId NUMBER;
    vRestoHisSql VARCHAR2(32767);
BEGIN
    
	SELECT USER_ID into vUserId FROM USERS WHERE MAIL_ADDRESS = P_MAIL_ADDRESS AND USER_ROLE = 'ROLE_RESTAURANT_ADMIN';
    DBMS_OUTPUT.PUT_LINE('ユーザーID: ' || vUserId);
	
	vSql := 'SELECT RESTAURANT_ID FROM RESTO_ACCOUNTS WHERE USER_ID = ' || vUserId;
    EXECUTE IMMEDIATE vSql INTO vRestaurantId;
    DBMS_OUTPUT.PUT_LINE('飲食店ID: ' || vRestaurantId);
    
    vRestoHisSql := 'RESTAURANT_HISTORY_ID IN (SELECT RESTAURANT_HISTORY_ID FROM RESTO_HISTORIES WHERE RESTAURANT_ID = ' || vRestaurantId || ')';
    vSql := 'DELETE FROM RESTO_NAMES WHERE ' || vRestoHisSql;
    EXECUTE IMMEDIATE vSql;

    vSql := 'DELETE FROM RESTO_HISTORIES WHERE RESTAURANT_ID = ' || vRestaurantId;
    EXECUTE IMMEDIATE vSql;

    vSql := 'DELETE FROM RESTO_ACCOUNTS WHERE RESTAURANT_ID = ' || vRestaurantId;
    EXECUTE IMMEDIATE vSql;

    vSql := 'DELETE FROM LOGIN_REQUESTS WHERE USER_ID = ' || vUserId;
    EXECUTE IMMEDIATE vSql;

    vSql := 'DELETE FROM USERS WHERE USER_ID = ' || vUserId;
    EXECUTE IMMEDIATE vSql;

    COMMIT;
END;