- name: "HashiCorp Vault | zipファイルをダウンロードする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  get_url:
    url: "{{ hashicorp_vault_zip_url }}"
    dest: "{{ hashicorp_vault_zip_dest }}"
    checksum: "{{hashicorp_vault_zip_checksum}}"

- name: "HashiCorp Vault | zipファイルを展開して実行ファイルを配置する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  unarchive:
    src:  "{{ hashicorp_vault_zip_dest }}"
    dest:  "{{ hashicorp_vault_bin_dest }}"
    remote_src: yes

- name: "HashiCorp Vault | Vaultを設定する"
  ignore_errors: "{{ ansible_check_mode }}"
  shell:
    cmd: |
      vault -autocomplete-install
      complete -C /usr/local/bin/vault vault

- name: "HashiCorp Vault | mlockのシステムコールをrootでなくても実行可能にする"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  shell:
    cmd: setcap cap_ipc_lock=+ep /usr/local/bin/vault

- name: "HashiCorp Vault | Vault用のユーザーを追加する"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  user:
    home: "{{ hashicorp_vault_etc_dir_root_path }}"
    name: "{{ hashicorp_vault_name }}"
